[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustdocflags = [
  "--cfg=web_sys_unstable_apis",
  "--cfg=getrandom_backend=\"wasm_js\"",
]
rustflags = [
  "--cfg=web_sys_unstable_apis",
  "--cfg=getrandom_backend=\"wasm_js\"",
]
