[package]
description = "bevy_replicon backend implementation using aeronet"
name = "aeronet_replicon"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
## Enables client-side items.
client = ["bevy_replicon/client"]

## Enables server-side items.
server = ["bevy_replicon/server"]

[dependencies]
aeronet = { workspace = true, features = ["bevy"] }

ahash = { workspace = true }
bimap = { workspace = true }
bytes = { workspace = true }
derivative = { workspace = true }
tracing = { workspace = true }

bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_time = { workspace = true }

bevy_replicon = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }
serde = { workspace = true }
